2024-10-16 10:14:34,162 ERROR: Exception on /book/Hotel/1 [POST] [in C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\app\views.py", line 677, in book
    session['booking_date_str'] = datetime.utcnow().strftime('%Y-%m-%d-%H-%M-%s')
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Invalid format string
2024-10-16 12:44:42,956 ERROR: Exception on /register [POST] [in C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\app\views.py", line 105, in register
    new_user = User(
               ^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2167, in _declarative_constructor
    raise TypeError(
TypeError: 'password' is an invalid keyword argument for User
2024-10-16 12:45:35,086 ERROR: Exception on /register [POST] [in C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\app\views.py", line 105, in register
    new_user = User(
               ^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 571, in _initialize_instance
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\sqlalchemy\orm\decl_base.py", line 2167, in _declarative_constructor
    raise TypeError(
TypeError: 'password' is an invalid keyword argument for User
2024-10-16 12:55:54,562 ERROR: Exception on /cancel-booking/1 [POST] [in C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\app\views.py", line 398, in cancel_booking
    return redirect(url_for('profile'))
                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\helpers.py", line 220, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\flask\app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\700041\Documents\vrajesh_flask\v_project\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'profile'. Did you mean 'routes.profile' instead?
2024-10-16 14:55:15,594 INFO: Starting operation: Fetching user profile for editing [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:15]
2024-10-16 14:55:15,598 INFO: Finished operation: Fetching user profile for editing in 0.00 seconds [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:25]
2024-10-16 14:59:19,608 INFO: Starting operation: Fetching user profile for editing [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:15]
2024-10-16 14:59:19,612 INFO: Finished operation: Fetching user profile for editing in 0.00 seconds [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:25]
2024-10-16 14:59:29,312 INFO: Starting operation: Fetching user profile for editing [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:15]
2024-10-16 14:59:29,314 INFO: Finished operation: Fetching user profile for editing in 0.00 seconds [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:25]
2024-10-16 14:59:29,396 INFO: Starting operation: Updating user profile [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:15]
2024-10-16 14:59:29,728 INFO: Finished operation: Updating user profile in 0.33 seconds [in C:\Users\700041\Documents\vrajesh_flask\v_project\app\context_managers.py:25]
